[package]
name = "maciej_the_bot"
version = "0.2.0"
authors = ["xavrax"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
