[package]
name = "maciej_the_bot"
version = "0.1.0"
authors = ["xavrax"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.9.0"
lazy_static = "1.4.0"

[dependencies.serenity]
version = "0.8.0"
features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]
