[package]
name = "maciej-the-bot"
version = "0.2.0"
authors = ["xavrax"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
structopt = "0.3"
serenity = "0.10"

[dev-dependencies]
cucumber_rust = { version="0.8", features=["macros"] }
